"""Structured JSON logger used by every experiment script.

Each line is a self-contained JSON record. The tables in the paper are
generated by aggregating these records via a companion script; we keep
the format flat and string-keyed so that downstream parsing is trivial.
"""
from __future__ import annotations

import io
import json
import os
import time
from typing import Any, Dict, Optional


class JSONLogger:
    """Append-only JSON-lines logger with optional stdout mirror."""

    def __init__(self, path: str, mirror_stdout: bool = False) -> None:
        assert path, "logger path must be a non-empty string"
        self.path = path
        self.mirror_stdout = mirror_stdout
        os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
        self._fh: Optional[io.TextIOBase] = open(path, "a", encoding="utf-8")

    def log(self, record: Dict[str, Any]) -> None:
        assert self._fh is not None, "logger has been closed"
        record = {"ts": time.time(), **record}
        line = json.dumps(record, ensure_ascii=False, sort_keys=True)
        self._fh.write(line + "\n")
        self._fh.flush()
        if self.mirror_stdout:
            print(line)

    def close(self) -> None:
        if self._fh is not None:
            self._fh.close()
            self._fh = None

    def __enter__(self) -> "JSONLogger":
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.close()
